[rewrite_local]]
^https:\/\/www\.themepro\.ca\/api\/(\d+)$ url request-header (\r\n[^\r\n]+) request-header $1api/$2
^https:\/\/www\.themepro\.ca\/api\/\d+$ url response-body "screen_id":\s*".*?" response-body "screen_id": "ssbwai"
  
[mitm]
enable = true
hostname = www.themepro.ca
