[rewrite_local]]
^https:\/\/ecustomer\.cntaiping\.com\/campaignsms\/coin\/exchange\/twoPage\?id=(\d+)$ url request-header (\r\nid=\d+) request-header $1id=$2

^https:\/\/ecustomer\.cntaiping\.com\/campaignsms\/coin\/exchange\/twoPage\?id=\d+$ url response-body "isLootAll":\d+ response-body "isLootAll":0

[mitm]
enable = true
hostname = ecustomer.cntaiping.com
