

[rewrite_local]]
^https:\/\/ad-task-center\.xiaohongshu\.com\/api\/adtaskcenter\/daka/query-task-progress url response-body (\s*"activityStatus"\s*:\s*)(\d+) response-body $12

[mitm]
enable = true
hostname = ad-task-center.xiaohongshu.com
