[rewrite_local]
# 调试响应体
^https:\/\/ad-task-center\.xiaohongshu\.com\/api\/adtaskcenter\/daka/query-task-progress url response-body .+ response-body console.log("[Modified] activityStatus=2")

# 正式修改规则
^https:\/\/ad-task-center\.xiaohongshu\.com\/api\/adtaskcenter\/daka/query-task-progress url response-body (\"activityStatus\"\s*:\s*)\d+ response-body $12

[mitm]
hostname = ad-task-center.xiaohongshu.com
